static_analyses:
  ignore_files: []
  ignore_unused_requirements: []
  ignore_missing_requirements:
    - configobj
downstream_dependencies: 
  - mycoplasma_pneumoniae
  - rand_wc_model_gen
email_notifications:
  - balazs.szigeti@mssm.edu
  - jonrkarr@gmail.com
